FROM python:3.12-slim
WORKDIR /app
RUN pip install gunicorn==25.3.0
COPY backend/requirements.txt .
RUN pip install -r requirements.txt --no-cache-dir
COPY backend/ .
COPY data/ /data/
CMD ["gunicorn", "--bind", "0.0.0.0:8000", "foodgram.wsgi"] 
