# Generated by Django 6.0.5 on 2026-05-13 14:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_alter_favorite_recipe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='recipeingredient',
            name='quantity',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='measurement_unit',
            field=models.CharField(choices=[('g', 'грамм'), ('kg', 'килограмм'), ('ml', 'миллилитр'), ('l', 'литр'), ('pcs', 'штук'), ('tsp', 'чайная ложка'), ('tbsp', 'столовая ложка'), ('cup', 'стакан'), ('pinch', 'щепотка')], default='g', max_length=64, verbose_name='Единица измерения'),
        ),
        migrations.AddField(
            model_name='recipeingredient',
            name='amount',
            field=models.PositiveSmallIntegerField(default=100, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(32000)], verbose_name='Количество'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(max_length=128, unique=True, verbose_name='Название ингредиента'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(upload_to='recipes/images/', verbose_name='Ссылка на картинку на сайте'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=32, unique=True, verbose_name='Уникальное название'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(max_length=32, unique=True, verbose_name='Уникальный слаг'),
        ),
    ]
