# Generated by Django 5.1.1 on 2026-05-05 15:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='following',
            field=models.ManyToManyField(related_name='followers', through='recipes.Follow', to=settings.AUTH_USER_MODEL, verbose_name='Подписки'),
        ),
    ]
